site_name: Dash, .NET Tool for fast model-driven code generation
nav:
    - Home: index.md
    - Introduction:
        - Getting Started: introduction/getting-started.md
    - User Guide:
        - Writing Your Model: user-guide/writing-your-model.md
        - Writing Your Custom Templates: user-guide/custom-templates.md

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - cs
        - json
