site_name: Dash
site_description: Documentation for dotnet dash cli tool
site_author: Huy Hoang

repo_url: https://github.com/dotnet-dash/dash

nav:
    - Home: index.md
    - Model File:
        - Introduction: model-file/introduction.md
        - Configuration Section: model-file/configuration-section.md
        - Entities In-Depth: model-file/entities-in-depth.md
        - Data Type Declaration: model-file/data-type-declaration.md
        - Seeding data: model-file/seeding-data.md
    - Templates:
        - Built-in Templates: template/built-in-templates.md
        - Custom Templates: template/custom-templates.md
    - Examples:
        - Country And Currency: examples/country-and-currency.md

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - cs
        - json

markdown_extensions:
    - admonition

copyright: Copyright &copy; 2020 Huy Hoang