site_name: Dash, .NET Tool for fast model-driven code generation
nav:
    - Home: index.md
    - Introduction:
        - The Big Picture: introduction/the-big-picture.md
        - Contributing: introduction/contributing.md
        - Getting Started: introduction/getting-started.md
    



    - 
    - Model: model.md
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - cs
        - json
