site_name: Dash
site_description: Documentation for dotnet dash cli tool
site_author: Huy Hoang

repo_url: https://github.com/dotnet-dash/dash

nav:
    - Home: index.md
    - Model File:
        - Introduction: model-file/introduction.md
        - Defining Relationships: model-file/defining-relationships.md
        - Seeding data: model-file/seeding-data.md
        - Inheritance: model-file/inheritance.md
    - Templates:
        - Built-in Templates: templates/built-in-templates.md
        - Custom Templates: templates/custom-templates.md
    - Examples:
        - Country And Currency: examples/country-and-currency.md

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - cs
        - json

markdown_extensions:
    - admonition

copyright: Copyright &copy; 2020 Huy Hoang