﻿// <auto-generated>
// This code was generated by Dash.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Nnn // 
{
    public partial class Base
    {
        public int Id { get; set; }
    }

    public partial class Order
    {
        public int Id { get; set; }
        [StringLength(100)]
        public string Description { get; set; }
        public ICollection<OrderProduct> OrderProduct { get; set; }
    }

    public partial class Product
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string LargerDescription { get; set; }
        public ICollection<OrderProduct> OrderProduct { get; set; }
    }

    public partial class OrderProduct
    {
        public int Id { get; set; }
        public ICollection<Order> Order { get; set; }
        public ICollection<Product> Product { get; set; }
    }
}