name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./src/Dash/src
    - name: Build
      run: dotnet build ./src/Dash/src --configuration Release --no-restore
    - name: Test
      run: dotnet test ./src/Dash/src --no-restore --verbosity normal
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.3
      with:
        # Set the sonar.projectBaseDir analysis property
        projectBaseDir: /src/Dash/src # optional, default is .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
